obstacles:
  - corners:
    - [2.0, 2.0]
    - [2.0, 1.8]
    - [1.0, 1.8]
    - [1.0, 2.0]
viewpoints:
  - x: 1.5
    y: 0.5
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 1.0
    qw: 0.0
    frame_id: "map"
  - x: 1.2
    y: 3.2
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0
    frame_id: "map"
